---
name: "TPC-H Central All-Runner"
env:
  INPUT_exchange-strategy: "${{ github.event.inputs.exchange-strategy }}"
  INPUT_extra: "${{ github.event.inputs.extra }}"
  INPUT_fail-fast: "${{ github.event.inputs.fail-fast }}"
  INPUT_join-strategy: "${{ github.event.inputs.join-strategy }}"
  INPUT_scale: "${{ github.event.inputs.scale }}"
  INPUT_serializer: "${{ github.event.inputs.serializer }}"
  INPUT_use-cyclone: "${{ github.event.inputs.use-cyclone }}"
  INPUT_ve-log-debug: "${{ github.event.inputs.ve-log-debug }}"
"on":
  workflow_dispatch:
    inputs:
      exchange-strategy:
        type: "choice"
        description: "Exchange strategy"
        options:
        - "spark"
        - "vector-host"
        - "none"
        default: "spark"
      extra:
        type: "input"
        description: "Extra command line arguments to add to Spark"
      fail-fast:
        type: "boolean"
        description: "Fail Fast"
        default: "true"
      join-strategy:
        type: "choice"
        description: "Join strategy"
        options:
        - "-"
        - "host"
        - "spark"
        default: "-"
      scale:
        type: "choice"
        description: "Scale"
        options:
        - "1"
        - "10"
        - "20"
        default: "1"
      serializer:
        type: "choice"
        description: "Serializer"
        options:
        - "-"
        - "com.nec.spark.planning.VeCachedBatchSerializer"
        - "com.nec.cache.ArrowBasedCacheSerializer"
        - "com.nec.cache.InVectorEngineCacheSerializer"
        default: "-"
      use-cyclone:
        type: "boolean"
        description: "Enable Spark Cyclone plugin?"
        default: "true"
      ve-log-debug:
        type: "boolean"
        description: "Debug VE logs"
        default: "false"
jobs:
  build:
    runs-on: "ve"
    timeout-minutes: 20
    steps:
    - uses: "actions/checkout@v2"
    - name: "Check User"
      run: "whoami"
    - name: "Check Path"
      run: "pwd"
    - name: "Check Access to VE"
      run: "/opt/nec/ve/bin/vecmd info"
    - name: "Branch Ref"
      run: "echo ${GITHUB_REF#refs/heads/}"
    - name: "Run TPC-H"
      run: "sbt tpcbench-run/run"
      if: "success()"
    - name: "Copying to sparkcyclone.io"
      if: "always()"
      run: "rsync -r -v tpcbench-run/target/tpc-html/ egonzalez@xpressai.jp:/var/www/sparkcyclone.io/tpc-html/summary"
    strategy:
      matrix:
        query:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
    env:
      INPUT_query: "${{ matrix.query }}"
